### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by JameChen** [wuzuchang/SmallestWidthPlugin#2]
感觉算错了吧，填1080px，生成540dp看里面的值  <dimen name="sw_540dp">270.0dp</dimen>在dpi320机上不应该是540dp才是吗怎么是270dp?

**Comment by JameChen** [comment]
<dimen name="sw_540dp">270.0dp</dimen>

**Comment by JameChen** [comment]
/*<dimen name="sw_540dp">270.0dp</dimen>*/

**Comment by wuzuchang** [comment]
你设计稿是1080px，如果你设备最小宽度是sw540dp。那么540dp要被平均分成1080份，一份就是0.5dp，540份就是270dp。
dpi320机不一定就是找sw540dp下的值。公式：SmallestWidth(dp) = px / (dpi / 160) 。只有你屏幕最小宽度是1080px，系统才会去匹配对应的 values-sw540dp文件夹。

**Comment by wuzuchang** [comment]
我生成的dimen最大值没有设置到很大（下个版本修改一下），如果生成到sw1080dp = 540dp。假设你现在设计搞最小宽度是1080px，里面有个控件宽度就是1080px，你在activity中使用sw1080dp，不就是现在设备的最小宽度了么。

**Comment by JameChen** [comment]
我怎么感觉输入的宽度是设计图dp单位你看文件生成尺寸就知道输入540dp,它生成sw540文件里面才是1dp

**Comment by JameChen** [comment]
假设你现在设计搞最小宽度是1080px，里面有个控件宽度就是1080px，你在activity中使用sw1080dp，不就是现在设备的最小宽度了么。这句错了吧手机1080px他是匹配到sw540的而不是sw1080,你们都没试过吗

**Comment by wuzuchang** [comment]
SmallestWidth适配就是，你设计稿里面控件是n*mpx，那么你在Activity里也设置sw_ndp*sw_mdp就行。 手机最小宽度是1080px，dpi320 那么匹配到的是values-sw540dp。你设计稿控件宽是1080px，你Activity里使用sw_1080dp （sw_1080dp = 540dp）。 540dp就是你整个屏幕的宽度。

**Comment by wuzuchang** [comment]
SmallestWidth适配就是，你设计稿里面控件是`n*mpx`，那么你在Activity里也设置`sw_ndp*sw_mdp`就行。 手机最小宽度是1080px，dpi320 那么匹配到的是values-sw540dp。你设计稿控件宽是1080px，你Activity里使用sw_1080dp （sw_1080dp = 540dp）。 540dp就是你整个屏幕的宽度。

**Comment by JameChen** [comment]
怎么视频横屏？

**Comment by JameChen** [comment]
横屏怎么适配？

**Comment by wuzuchang** [comment]
不管横屏竖屏，按最小的宽度计算。

**Comment by JameChen** [comment]
不是呀在横屏里没有适配到呀

**Comment by JameChen** [comment]
比如sw540里横屏540dp没有铺满只有最小540dp,那怎么写最大值

**Comment by wuzuchang** [comment]
哦，我昨天更新了一个版本，里面的值有做修改，如果设计稿的最小宽度值M>设备最小宽度值N，则dimens.xml里面的最大值为 `2*M`，反之则是`2*N` ,如 设计稿最小宽度是1080px，社保最小宽度是540dp，则取值范围为_sw_2160dp~sw_2160dp

**Comment by wuzuchang** [comment]
哦，我昨天更新了一个版本，里面的值有做修改，如果设计稿的最小宽度值M>设备最小宽度值N，则dimens.xml里面的最大值为 2*M，反之则是2*N ,如 设计稿最小宽度是1080px，设备最小宽度是540dp，则取值范围为_sw_2160dp~sw_2160dp

**Comment by JameChen** [comment]
要卸载重装？

**Comment by wuzuchang** [comment]
不需要，v1.0.5版本，应该还在审核。到时候更新一下，重新填一下设计稿最小尺寸和要添加的`values-sw<N>dp`文件夹生成一下就行。里面会判断dimens 下name属性的值，存在的话会修改，不存在会添加。

**Comment by JameChen** [comment]
没有呀存在他还添加重复老是要删除麻烦死

**Comment by wuzuchang** [comment]
你现在的版本是1.0.5？或者你可以把所有的`values-sw<N>dp`和values文件夹下的dimens.xml一次性删掉重新生成一份.

**Comment by JameChen** [comment]
please enter a three-dight number?

**Comment by wuzuchang** [comment]
你输入了多少？

**Comment by JameChen** [comment]
1080

**Comment by wuzuchang** [comment]
你屏幕最小尺寸要values-sw1080dp？

**Comment by wuzuchang** [comment]
1.通过Add smallestWidth添加需要的屏幕最小尺寸，如540，则会生成values-sw540dp文件夹
2.Design Width 为你设计稿的尺寸，如1080px

**Comment by JameChen** [comment]
一般好像300-600？

**Comment by wuzuchang** [comment]
是的，通过公式计算：SmallestWidth(dp) = px / (dpi / 160)，px就是你屏幕的最小宽度，单位px。

**Comment by JameChen** [comment]
话说横屏怎么适配？

**Comment by wuzuchang** [comment]
插件版本1.0.5会生成在dimens.xml下生成更大的值，现在1.0.4的值没有写到很大。可以等1.0.5更新，也可以自己在dimens.xml手动添加自己需要的值。

**Comment by JameChen** [comment]
分辨率最高3840都有-oo-

**Comment by wuzuchang** [comment]
sw适配不是按最高分辨率去适配的。是要 取设备最小宽度/(设备的dpi/160)

**Comment by JameChen** [comment]
感觉这样也适配不了横屏吧比如108081920手机，我竖屏sw1080dp (540dp)，横屏难道要改成sw1920()，静态布局肯定做不了都写死了

**Comment by wuzuchang** [comment]
横屏还是找的values-sw540dp文件夹下的值。最小宽度，不管你横屏竖屏，最小宽度是不变的。你竖屏的时候，最小宽度是1080。你横屏的时候，高就变成了最小宽度，还是1080。

**Comment by JameChen** [comment]
所以总结是平板适配不了

**Comment by JameChen** [comment]
横屏是找values-sw540dp文件夹下的值呀，但之前写1080dp不是铺满罗，因为在竖屏是铺满长度

**Comment by JameChen** [comment]
话说字体怎么适配

**Comment by wuzuchang** [comment]
那你要做横竖屏适配。不可能横竖屏用同一尺寸能适配的，横屏和竖屏的设计稿里面的控件尺寸也不可能是一样的。横屏的设计稿铺满他里面可能标注的就是1920px。
字体也可以用sw_ndp，系统最后把dp sp都会转化成像素px

**Comment by JameChen** [comment]
话说字体怎么适配大佬

**Comment by wuzuchang** [comment]
字体大小也使用`sw_<n>dp`，如：android:textsize = "@dimen/sw_15dp"

**Comment by JameChen** [comment]
这样你字体就不能随系统改变了

**Comment by wuzuchang** [comment]
1.0.6版本加了字体适配

**Comment by JameChen** [comment]
啥，怎么适配哥讲解一下，是用sp吗

**Comment by wuzuchang** [comment]
1.0.6还在审核，使用 : android:textSize = "@dimen/sw_16sp"。

**Comment by JameChen** [comment]
sw是 float dpValue =   (pxValue/(float)designWidth) * sw;字体适配是怎么算的，

**Comment by wuzuchang** [comment]
字体也是一样算的，dp 和 sp 是没什么区别的，只是sp会随你系统设置字体大小改变而改变

**Comment by JameChen** [comment]
好像也是哦

**Comment by JameChen** [comment]
能不能改输入一个范围值生成，感觉这样一个个ADD比较麻烦

**Comment by wuzuchang** [comment]
你是说values-sw<N>dp文件夹么

**Comment by JameChen** [comment]
是罗要不加个范围选项

**Comment by wuzuchang** [comment]
那这样输入400~500，这样会生成100个文件夹。可以加个按“,”分割，这样就可以同时输入多个想要添加的文件夹

**Comment by JameChen** [comment]
意思给我们2个选择，一种是一个个添加，另一种开始值和结束值范围

**Comment by JameChen** [comment]
要多久1.0.6才审核过

**Comment by wuzuchang** [comment]
我昨天晚上提交的审核，审核一般是2天内

**Comment by JameChen** [comment]
-你项目有用这个适配吗还是用今日头条？

**Comment by wuzuchang** [comment]
我自己的用的是sw适配，因为有用到第三方UI库，头条对第三方库会出现不适配

**Comment by JameChen** [comment]
怎么没看到1.0.6？

**Comment by wuzuchang** [comment]
刚通知审核通过

**Comment by JameChen** [comment]
没看到呀

**Comment by JameChen** [comment]
字体就40？

**Comment by JameChen** [comment]
太少了吧

**Comment by JameChen** [comment]
在吗，加多点呗

**Comment by wuzuchang** [comment]
还要加么，加到多少？

**Comment by JameChen** [comment]
你没用吗？加到宽度一样看看

**Comment by wuzuchang** [comment]
字体不需要那么大吧

**Comment by JameChen** [comment]
你现在太少了

**Comment by wuzuchang** [comment]
平常字体10sp~25sp就够了吧

**Comment by JameChen** [comment]
25sp哪够你这样人家做放大字体都做不到

**Comment by wuzuchang** [comment]
我加到60sp了，够么

**Comment by JameChen** [comment]
加100看看哈哈

**Comment by wuzuchang** [comment]
好吧
