### ISSUE TITLE
Alt+P 无法选择module

### ISSUE THREAD

**Issue by AndroidXinDong** [wuzuchang/SmallestWidthPlugin#3]
通过快捷键跳出窗口之后，choice module里面 只有 specify the module relative path 没有app模块选项是怎么回事

**Comment by AndroidXinDong** [comment]
输入相对路径也没有地方输入啊

**Comment by wuzuchang** [comment]
方便发一下settings.gradle内容么，晚上回去修复一下这个情况

**Comment by AndroidXinDong** [comment]
include ':app'
rootProject.name='ScreenAdapterDemo'

单一module的情况下是不能自动弹出选项的，我是随便引了一个module才仅仅弹出了APP这个module 大佬您看看怎么肥事吧

**Comment by wuzuchang** [comment]
好的，我这边昨天晚上更新了个版本，你可以在plugin文件夹下下载1.2.0版本，本地安装试一下。
