### ISSUE TITLE
新版本建议新增功能

### ISSUE THREAD

**Issue by 123ufo** [wuzuchang/SmallestWidthPlugin#4]
建议新版本可以添加一个功能，可以自定义前缀和和后缀的功能。例如sw_375dp，可以自定义生成为375rdp。

**Comment by wuzuchang** [comment]
好的

**Comment by wuzuchang** [comment]
已经更新了

**Comment by 123ufo** [comment]
好的，速度很快，但是我在AS的插件里还没有看到有更新的版本

**Comment by wuzuchang** [comment]
应该还在审核

**Comment by wuzuchang** [comment]
> 好的，速度很快，但是我在AS的插件里还没有看到有更新的版本

Android Studio 插件可以搜索到了新版本了
